-- ziiiTV core baseline
-- This migration intentionally precedes every historical incremental migration.
-- It makes a brand-new Supabase project reproducible without SQL Editor steps.

create extension if not exists pgcrypto;
create extension if not exists "uuid-ossp";

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'user' check (role in ('user', 'admin')),
  m3u_url text,
  last_processed timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.canonical_titles (
  id text primary key,
  slug text not null unique,
  title text not null,
  alt_titles text[] not null default '{}',
  type text not null check (type in ('movie', 'series')),
  streaming text not null default 'outros',
  match_hints text[] not null default '{}',
  genres text[] not null default '{}',
  tmdb_id integer,
  year text,
  rating numeric(3,1),
  overview text,
  poster text,
  backdrop text,
  director text,
  age_rating text,
  duration integer,
  trailer_url text,
  priority boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.homes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists homes_single_active_idx
  on public.homes (is_active) where is_active;

create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  url_original text not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'ready', 'error')),
  channel_count integer not null default 0 check (channel_count >= 0),
  error_message text,
  processed_at timestamptz,
  presentation_mode text not null default 'auto' check (presentation_mode in ('auto', 'curated')),
  last_synced_at timestamptz,
  content_count integer not null default 0 check (content_count >= 0),
  home_id uuid references public.homes(id) on delete set null,
  content_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pairing_codes (
  code text primary key check (code ~ '^ZIII-[A-Z2-9]{4}$'),
  user_id uuid not null references public.users(id) on delete cascade,
  playlist_id uuid references public.playlists(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  last_used_at timestamptz
);

create table if not exists public.channels (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  streams jsonb not null default '[]'::jsonb check (jsonb_typeof(streams) = 'array'),
  group_name text,
  logo_url text,
  canonical_id text references public.canonical_titles(id) on delete set null,
  streaming text,
  content_type text check (content_type is null or content_type in ('live', 'movie', 'series', 'show', 'standup')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  device_id text,
  channel_id uuid references public.channels(id) on delete set null,
  canonical_id text references public.canonical_titles(id) on delete set null,
  channel_name text not null,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  progress_pct integer not null default 0 check (progress_pct between 0 and 100),
  watched_at timestamptz not null default now()
);

create table if not exists public.watch_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  device_id text,
  channel_id uuid references public.channels(id) on delete set null,
  canonical_id text references public.canonical_titles(id) on delete set null,
  event_type text not null default 'play',
  position_seconds integer not null default 0 check (position_seconds >= 0),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.home_sections (
  id uuid primary key default gen_random_uuid(),
  home_id uuid not null references public.homes(id) on delete cascade,
  title text not null,
  subtitle text,
  type text not null,
  source text,
  sort_order integer not null default 0,
  active boolean not null default true,
  config jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.section_items (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.home_sections(id) on delete cascade,
  canonical_id text references public.canonical_titles(id) on delete cascade,
  title_override text,
  poster_override text,
  backdrop_override text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (section_id, canonical_id)
);

create table if not exists public.enrich_jobs (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'running', 'paused', 'done', 'error')),
  processed_count integer not null default 0 check (processed_count >= 0),
  linked_count integer not null default 0 check (linked_count >= 0),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Legacy pairing tables are retained for a zero-downtime transition. Credentials
-- are never readable by anon/authenticated roles; the replacement flow uses Edge
-- Functions and private/Vault storage.
create table if not exists public.pair_tokens (
  id uuid primary key default gen_random_uuid(),
  token text not null unique default upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 8)),
  device_id text not null,
  device_name text,
  device_model text,
  status text not null default 'pending' check (status in ('pending', 'linked', 'expired')),
  playlist_url text,
  playlist_type text check (playlist_type is null or playlist_type in ('m3u', 'xtream')),
  xtream_host text,
  xtream_user text,
  xtream_pass text,
  user_id uuid references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  linked_at timestamptz
);

create table if not exists public.tv_sessions (
  id uuid primary key default gen_random_uuid(),
  device_id text not null unique,
  device_name text,
  device_model text,
  playlist_url text,
  playlist_type text check (playlist_type is null or playlist_type in ('m3u', 'xtream')),
  xtream_host text,
  xtream_user text,
  xtream_pass text,
  user_id uuid references public.users(id) on delete cascade,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.copa_matches (
  id text primary key,
  home_team_name text,
  home_team_short text,
  home_team_crest text,
  away_team_name text,
  away_team_short text,
  away_team_crest text,
  utc_date timestamptz not null,
  status text not null default 'SCHEDULED',
  minute integer,
  score_home integer,
  score_away integer,
  match_group text,
  stage text,
  venue text,
  matchday integer,
  updated_at timestamptz not null default now()
);

create table if not exists public.copa_standings (
  id bigint generated by default as identity primary key,
  group_name text not null,
  position integer not null,
  team_name text not null,
  team_short text,
  team_crest text,
  points integer not null default 0,
  played integer not null default 0,
  won integer not null default 0,
  draw integer not null default 0,
  lost integer not null default 0,
  goals_for integer not null default 0,
  goals_against integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (group_name, position)
);

create index if not exists idx_playlists_user_id on public.playlists(user_id);
create index if not exists idx_playlists_status on public.playlists(status);
create index if not exists idx_playlists_content_hash on public.playlists(content_hash) where content_hash is not null;
create index if not exists idx_pairing_codes_user_id on public.pairing_codes(user_id);
create index if not exists idx_pairing_codes_expires_at on public.pairing_codes(expires_at);
create index if not exists idx_channels_playlist_id on public.channels(playlist_id);
create index if not exists idx_channels_user_id on public.channels(user_id);
create index if not exists idx_channels_canonical_id on public.channels(canonical_id);
create index if not exists idx_channels_type_streaming on public.channels(content_type, streaming);
create index if not exists idx_watch_history_user_time on public.watch_history(user_id, watched_at desc);
create index if not exists idx_watch_history_device_time on public.watch_history(device_id, watched_at desc);
create index if not exists idx_home_sections_home_order on public.home_sections(home_id, sort_order);
create index if not exists idx_section_items_section_order on public.section_items(section_id, sort_order);
create index if not exists idx_pair_tokens_token_status on public.pair_tokens(token, status);
create index if not exists idx_pair_tokens_device on public.pair_tokens(device_id);
create index if not exists idx_tv_sessions_device on public.tv_sessions(device_id);
create index if not exists idx_copa_matches_date on public.copa_matches(utc_date);

create or replace function public.update_updated_at_column()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.users (id, email, role)
  values (new.id, coalesce(new.email, new.id::text || '@invalid.local'), 'user')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.users
    where id = auth.uid() and role = 'admin'
  );
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

do $$
declare table_name text;
begin
  foreach table_name in array array['users', 'playlists', 'homes', 'home_sections', 'enrich_jobs', 'tv_sessions'] loop
    execute format('drop trigger if exists %I on public.%I', 'touch_' || table_name || '_updated_at', table_name);
    execute format('create trigger %I before update on public.%I for each row execute function public.update_updated_at_column()', 'touch_' || table_name || '_updated_at', table_name);
  end loop;
end $$;

create or replace function public.sync_linked_pair_token()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status = 'linked' and old.status is distinct from 'linked' then
    insert into public.tv_sessions (
      device_id, device_name, device_model, playlist_url, playlist_type,
      xtream_host, xtream_user, xtream_pass, user_id, last_seen_at
    ) values (
      new.device_id, new.device_name, new.device_model, new.playlist_url, new.playlist_type,
      new.xtream_host, new.xtream_user, new.xtream_pass, new.user_id, now()
    )
    on conflict (device_id) do update set
      device_name = excluded.device_name,
      device_model = excluded.device_model,
      playlist_url = excluded.playlist_url,
      playlist_type = excluded.playlist_type,
      xtream_host = excluded.xtream_host,
      xtream_user = excluded.xtream_user,
      xtream_pass = excluded.xtream_pass,
      user_id = excluded.user_id,
      last_seen_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists on_pair_token_linked on public.pair_tokens;
create trigger on_pair_token_linked after update of status on public.pair_tokens
for each row execute function public.sync_linked_pair_token();

alter table public.users enable row level security;
alter table public.playlists enable row level security;
alter table public.pairing_codes enable row level security;
alter table public.channels enable row level security;
alter table public.canonical_titles enable row level security;
alter table public.watch_history enable row level security;
alter table public.watch_events enable row level security;
alter table public.homes enable row level security;
alter table public.home_sections enable row level security;
alter table public.section_items enable row level security;
alter table public.enrich_jobs enable row level security;
alter table public.pair_tokens enable row level security;
alter table public.tv_sessions enable row level security;
alter table public.copa_matches enable row level security;
alter table public.copa_standings enable row level security;

create policy playlists_owner_read on public.playlists for select using (user_id = auth.uid());
create policy playlists_owner_insert on public.playlists for insert with check (user_id = auth.uid());
create policy playlists_owner_update on public.playlists for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy playlists_owner_delete on public.playlists for delete using (user_id = auth.uid());
create policy pairing_codes_owner_read on public.pairing_codes for select using (user_id = auth.uid());
create policy pairing_codes_owner_delete on public.pairing_codes for delete using (user_id = auth.uid());
create policy homes_admin_all on public.homes for all using (public.is_admin()) with check (public.is_admin());
create policy home_sections_admin_all on public.home_sections for all using (public.is_admin()) with check (public.is_admin());
create policy section_items_admin_all on public.section_items for all using (public.is_admin()) with check (public.is_admin());
create policy enrich_jobs_admin_all on public.enrich_jobs for all using (public.is_admin()) with check (public.is_admin());
create policy pair_tokens_owner_read on public.pair_tokens for select using (user_id = auth.uid());
create policy pair_tokens_owner_update on public.pair_tokens for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy tv_sessions_owner_read on public.tv_sessions for select using (user_id = auth.uid());
create policy copa_matches_public_read on public.copa_matches for select using (true);
create policy copa_standings_public_read on public.copa_standings for select using (true);

revoke all on public.pair_tokens, public.tv_sessions from anon, authenticated;
grant select (id, token, device_id, device_name, device_model, status, user_id, created_at, expires_at, linked_at)
  on public.pair_tokens to authenticated;
grant select (id, device_id, device_name, device_model, user_id, last_seen_at, created_at, updated_at)
  on public.tv_sessions to authenticated;

grant select on public.copa_matches, public.copa_standings to anon, authenticated;
